In [2]:
import yfinance as yf

msft = yf.Ticker("MSFT")

In [3]:
import yfinance as yf

msft = yf.Ticker("MSFT")

# get all stock info
msft.info

# get historical market data
hist = msft.history(period="1mo")

# show meta information about the history (requires history() to be called first)
msft.history_metadata

# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

# show share count
msft.get_shares_full(start="2022-01-01", end=None)

# show financials:
# - income statement
msft.income_stmt
msft.quarterly_income_stmt
# - balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet
# - cash flow statement
msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders
msft.insider_transactions
msft.insider_purchases
msft.insider_roster_holders

# show recommendations
msft.recommendations
msft.recommendations_summary
msft.upgrades_downgrades

# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

# show options expirations
msft.options

# show news
msft.news

# get option chain for specific expiration
opt = msft.option_chain('YYYY-MM-DD')
# data available via: opt.calls, opt.puts

2022-01-27 00:00:00-05:00    7496869888
2022-02-04 00:00:00-05:00    7800719872
2022-02-05 00:00:00-05:00    7496869888
2022-02-11 00:00:00-05:00    7496869888
2022-03-04 00:00:00-05:00    7605040128
                                ...
2024-04-20 00:00:00-04:00    7430439936
2024-04-23 00:00:00-04:00    7430439936
2024-04-25 00:00:00-04:00    7617019904
2024-04-25 00:00:00-04:00    7430439936
2024-04-26 00:00:00-04:00    7430439936
Length: 172, dtype: int64

In [4]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-03-27 00:00:00-04:00,424.440002,424.450012,419.010010,421.429993,16705000,0.0,0.0
2024-03-28 00:00:00-04:00,420.959991,421.869995,419.119995,420.720001,21871200,0.0,0.0
2024-04-01 00:00:00-04:00,423.950012,427.890015,422.220001,424.570007,16316000,0.0,0.0
2024-04-02 00:00:00-04:00,420.109985,422.380005,417.839996,421.440002,17912000,0.0,0.0
2024-04-03 00:00:00-04:00,419.730011,423.260010,419.089996,420.450012,16502300,0.0,0.0
2024-04-04 00:00:00-04:00,424.989990,428.670013,417.570007,417.880005,19370900,0.0,0.0
2024-04-05 00:00:00-04:00,420.010010,426.510010,418.320007,425.519989,16544300,0.0,0.0
2024-04-08 00:00:00-04:00,425.170013,427.279999,423.299988,424.589996,14272400,0.0,0.0
2024-04-09 00:00:00-04:00,426.440002,427.739990,421.619995,426.279999,12512300,0.0,0.0
2024-04-10 00:00:00-04:00,422.190002,424.029999,419.700012,423.260010,16216600,0.0,0.0
2024-04-11 00:00:00-04:00,425.820007,429.369995,422.359985,427.929993,17966400,0.0,0.0
2024-04-12 00:00:00-04:00,424.049988,425.179993,419.769989,421.899994,19232100,0.0,0.0
2024-04-15 00:00:00-04:00,426.600006,426.820007,413.429993,413.640015,20273500,0.0,0.0
2024-04-16 00:00:00-04:00,414.570007,418.399994,413.730011,414.579987,16765600,0.0,0.0
2024-04-17 00:00:00-04:00,417.250000,418.880005,410.329987,411.839996,15855500,0.0,0.0
2024-04-18 00:00:00-04:00,410.630005,411.890015,403.950012,404.269989,21029900,0.0,0.0
2024-04-19 00:00:00-04:00,404.029999,405.480011,397.769989,399.119995,30276500,0.0,0.0
2024-04-22 00:00:00-04:00,400.079987,402.850006,395.750000,400.959991,20286900,0.0,0.0
2024-04-23 00:00:00-04:00,404.239990,408.200012,403.059998,407.570007,15734500,0.0,0.0
2024-04-24 00:00:00-04:00,409.559998,412.470001,406.779999,409.059998,15065300,0.0,0.0
2024-04-25 00:00:00-04:00,394.029999,399.890015,388.029999,399.040009,40586500,0.0,0.0
2024-04-26 00:00:00-04:00,412.170013,413.000000,405.760101,406.320007,29512911,0.0,0.0